---
abstract: 'Data::FormValidator e-mail address constraint/filter'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-FormValidator-EmailValid
provides:
  Data::FormValidator::EmailValid:
    file: lib/Data/FormValidator/EmailValid.pm
    version: '0.05'
recommends:
  Net::DNS: '0'
requires:
  Data::FormValidator: '4'
  Email::Valid: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bleargh45/Data-FormValidator-Email
version: '0.05'
